version: '3.4'
services:
  pihole:
    image: pihole/pihole
    networks:
      pihole-dns:
        ipv4_address: 192.168.100.3
      internal:
    ports:
      - 5000:53
    environment:
      - FTLCONF_LOCAL_IPV4==192.168.100.3
      - PIHOLE_DNS_=192.168.100.4
      - WEBPASSWORD=pihole-admin
    depends_on:
      - unbound
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`pihole.docker.localhost`)
      - traefik.http.routers.pihole.entrypoints=web
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - traefik.http.middlewares.pihole-admin.addprefix.prefix=/admin
      - traefik.http.routers.pihole.middlewares=pihole-admin@docker
  unbound:
    image: alpinelinux/unbound
    networks:
      pihole-dns:
        ipv4_address: 192.168.100.4
    volumes:
      - ./config/pi-hole.conf:/etc/unbound/unbound.conf
  traefik:
    image: traefik
    networks:
      - internal
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./config/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    image: traefik/whoami
    networks:
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)
      - traefik.http.routers.whoami.entrypoints=web
networks:
  pihole-dns:
    name: pihole-dns
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1
          ip_range: 192.168.100.10/24
  internal:
    name: internal