version: '3.4'
services:

  # DNS and Adblocking
  pihole:
    image: pihole/pihole
    networks:
      - pihole-dns
      - internal
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      DHCP_ACTIVE: false
      DHCP_IPV6: false
      DNSSEC: true
      DNSMASQ_LISTENING: all
      PIHOLE_DNS_: unbound#53
      WEBPASSWORD: ${PIHOLE_PASS:-admin}
      TEMPERATUREUNIT: f
      TZ: America/New_York
    volumes:
      - ./data/pihole:/etc/pihole
      - ./data/dnsmasq.d:/etc/dnsmasq.d
    depends_on:
      - unbound
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.pihole.rule: Host(`pihole.${HOST}`)
      traefik.http.routers.pihole.entrypoints: web
      traefik.http.services.pihole.loadbalancer.server.port: 80
    restart: unless-stopped

  # Recursive DNS Resolution
  unbound:
    image: mvance/unbound
    networks:
      - pihole-dns
    restart: unless-stopped
    volumes:
      - ./config/unbound.conf:/opt/unbound/etc/unbound.conf
  traefik:
    image: traefik
    networks:
      - internal
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./config/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  # Smoke test container
  whoami:
    image: traefik/whoami
    restart: unless-stopped
    networks:
      - internal
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.rule: Host(`whoami.${HOST}`)
      traefik.http.routers.whoami.entrypoints: web
  
  # Monitoring
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    networks:
      - internal
    volumes:
      - ./data/uptime-kuma:/app/data
    labels:
      traefik.enable: true
      traefik.http.routers.uptime-kuma.rule: Host(`monitor.${HOST}`)
      traefik.http.services.uptime-kuma.loadbalancer.server.port: 3001
      traefik.http.routers.uptime-kuma.entrypoints: web
networks:
  pihole-dns:
    name: pihole-dns
  internal:
    name: internal
volumes:
  uptime-kuma: