version: '3.4'
services:
  pihole:
    image: pihole/pihole
    networks:
      - pihole-dns
      - internal
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      DHCP_ACTIVE: false
      DHCP_IPV6: false
      DNSSEC: true
      DNSMASQ_LISTENING: all
      PIHOLE_DNS_: unbound#53
      WEBPASSWORD: pihole-admin
      TEMPERATUREUNIT: f
      TZ: America/New_York
    depends_on:
      - unbound
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`pihole.docker.localhost`)
      - traefik.http.routers.pihole.entrypoints=web
      - traefik.http.services.pihole.loadbalancer.server.port=80
    restart: unless-stopped
  unbound:
    image: mvance/unbound
    networks:
      - pihole-dns
    restart: unless-stopped
  traefik:
    image: traefik
    networks:
      - internal
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./config/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  whoami:
    image: traefik/whoami
    networks:
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)
      - traefik.http.routers.whoami.entrypoints=web
networks:
  pihole-dns:
    name: pihole-dns
  internal:
    name: internal