# yaml-language-server $schema=https://json.schemastore.org/traefik-v3.json
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
    exposedByDefault: false

entrypoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
          permanent: true
  web-secure:
    address: :443
api:
  insecure: true

certificatesResolvers:
  main:
    acme:
      tlsChallenge: {}
